import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import io
import openai

# --------------------------
# CONFIG
# --------------------------
openai.api_key = "your_api_key_here"  # replace with your actual API key

st.set_page_config(page_title="AI Report Builder", page_icon="📊", layout="wide")
st.title("📊 Automatic Report Builder")
st.write("Upload your dataset and get instant insights + charts generated by AI.")

# --------------------------
# FILE UPLOAD
# --------------------------
uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])

if uploaded_file:
    # Read CSV
    df = pd.read_csv(uploaded_file)
    st.subheader("📋 Data Preview")
    st.dataframe(df.head())

    # --------------------------
    # BASIC STATS
    # --------------------------
    st.subheader("📈 Quick Summary")
    st.write(df.describe(include='all'))

    # --------------------------
    # CHARTS
    # --------------------------
    st.subheader("📊 Visualizations")

    numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
    for col in numeric_cols:
        fig, ax = plt.subplots()
        ax.hist(df[col].dropna(), bins=20)
        ax.set_title(f"Distribution of {col}")
        st.pyplot(fig)

    # --------------------------
    # AI REPORT GENERATION
    # --------------------------
    if st.button("🧠 Generate AI Report"):
        with st.spinner("Analyzing data..."):
            stats_text = df.describe(include='all').to_string()

            prompt = f"""
            You are a professional data analyst.
            Analyze the dataset summary below and write a concise report
            with trends, anomalies, and key takeaways.

            DATA SUMMARY:
            {stats_text}
            """

            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}]
            )

            report = response.choices[0].message.content
            st.success("✅ Report generated successfully!")
            st.subheader("📝 AI-Generated Report")
            st.write(report)
